name = "ppopgi-finalizer-bot"
main = "src/BotFinalizeLottery.ts"
compatibility_date = "2026-02-23"

# 🔁 Run every 1 minute
[triggers]
crons = ["*/2 * * * *"]

# Non-secret env vars (safe in git)
[vars]
REGISTRY_ADDRESS = "0xa916e20AbF4d57bCb98f7A845eb74f2EB4Dcbed2"
DEPLOYER_ADDRESS = "0xAd0c8Ba0E4e519B4EA97cE945A20E2716dDbDf7D"

RPC_URL = "https://rpc.ankr.com/etherlink_mainnet"
CRON_EVERY_MINUTES = "2"

MAX_TX = "10"
TIME_BUDGET_MS = "25000"
ATTEMPT_TTL_SEC = "600"

HOT_SIZE = "200"
COLD_SIZE = "100"

LOG_CHUNK_BLOCKS = "250"
BOOTSTRAP_LOOKBACK_BLOCKS = "50000"
DEPLOYER_HEAD_LAG_BLOCKS = "2"

TICKETS_LOOKBACK_BLOCKS = "2500"
TICKETS_ADDR_CHUNK = "50"
TICKETS_HEAD_LAG_BLOCKS = "2"

HATCH_EXTRA_DELAY_SEC = "300"

[[kv_namespaces]]
binding = "BOT_STATE"
id = "7be58949d65d4f4d8fa11bab19cbfb0c"

[durable_objects]
bindings = [
  { name = "BOT_LOCK", class_name = "BotLockDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BotLockDO"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1